MONGOCRYPT-269 create data key support for Azure
mongodb/libmongocrypt pull request #103
Opened 2020-09-10 18:46 UTC by kevinAlbs

2020-09-15 23:16 UTC, markbenvenuto requested changes

2020-09-16 13:50 UTC, kevinAlbs commented on src/mongocrypt-cache-oauth.c
> +#define MONGOCRYPT_OAUTH_CACHE_EVICTION_PERIOD_US 5000 * 5000
Ah typo, fixed.

2020-09-16 13:50 UTC, kevinAlbs commented on src/mongocrypt-ctx-datakey.c
> +                access_token,
Good catch. And now I realize I had not running with ASAN leak detection. I also caught a couple other leaks reported after running the `csfle` CLI test with leak detection. That will be tested in evergreen once we have credentials.

2020-09-16 13:50 UTC, kevinAlbs commented on src/mongocrypt-ctx-datakey.c
> +      bson_t oauth_response;
This is a view into the `kms.result` buffer. `_mongocrypt_buffer_to_bson` calls `bson_init_static` on the underlying buffer, which initializes the `bson_t` as a read-only view.

2020-09-16 18:22 UTC, markbenvenuto approved these changes

2020-09-16 18:26 UTC, merged