[WIP] macOS key loading support
mongodb/libmongocrypt pull request #107
Opened 2020-09-22 12:00 UTC by kevinAlbs

2020-09-22 12:55 UTC, kevinAlbs commented on kms-message/src/kms_crypto_apple.c
> +                             kSecKeyAlgorithmRSASignatureMessagePKCS1v15SHA256,
Aside, `kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256` is a distinct algorithm (and produces different results). I'm not sure what the difference is (my best guess is that it is the order of signing / hashing).

2020-09-22 12:58 UTC, kevinAlbs commented on kms-message/src/kms_crypto_apple.c
> +   SecExternalFormat format = kSecFormatUnknown;
I'm still not sure what the deal is here. I left this as `kSecFormatUnknown` for now.

2020-09-22 14:47 UTC, kevinAlbs commented on kms-message/src/kms_crypto_apple.c
> +   SecExternalFormat format = kSecFormatUnknown;
Per slack discussion, `kSecFormatWrappedPKCS8` is distinct from `PKCS8`.

2020-09-23 00:54 UTC, markbenvenuto requested changes

2020-09-23 00:54 UTC, markbenvenuto commented on kms-message/src/kms_crypto_apple.c
> +                             kSecKeyAlgorithmRSASignatureMessagePKCS1v15SHA256,
The SignatureDigest version expects a digest. The one you chose will do the digest of the message for you.

From the SecKey.h header:
 @constant kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256
    RSA signature with PKCS#1 padding, input data must be SHA-256 generated digest.

  @constant kSecKeyAlgorithmRSASignatureMessagePKCS1v15SHA256
    RSA signature with PKCS#1 padding, SHA-256 digest is generated from input data of any size.

2020-09-23 00:54 UTC, markbenvenuto commented on kms-message/src/kms_crypto_apple.c
> +      SecKeyCreateSignature (key_ref,
You need to check the return. You may want to check all the CFDataCreate also.

2020-09-23 19:20 UTC, markbenvenuto approved these changes

2020-09-25 21:09 UTC, merged