feat: build and test node on m1 NODE-3631
mongodb/libmongocrypt pull request #245
Opened 2022-02-08 16:17 UTC by alenakhineika

Add the `build-and-test-node` task to macOS M1 config.

2022-02-08 22:15 UTC, nbbeeken requested changes
Teensy tiny comment change, thanks for this!

2022-02-08 22:15 UTC, nbbeeken commented on bindings/node/.evergreen/prebuild.sh
>  # FLE platform matrix (as of Oct 7th 2021)
```suggestion
# FLE platform matrix (as of Feb 8th 2022)
```
I guess the date is also stored in git but why not keep this marked correctly

2022-02-09 17:54 UTC, nbbeeken approved these changes

2022-02-09 19:06 UTC, durran approved these changes

2022-02-09 19:07 UTC, merged

2022-07-25 17:35 UTC, sajadghawami commented
Still getting this error:

```
XXX/node_modules/mongodb-client-encryption: Command failed.
Exit code: 1
Command: prebuild-install --tag-prefix node-v || node-gyp rebuild
Arguments:
Directory: /XXX/node_modules/mongodb-client-encryption
Output:
prebuild-install WARN install No prebuilt binaries found (target=16.14.0 runtime=node arch=arm64 libc= platform=darwin)
```