feat(NODE-4241): add support for rewrapManyDataKey and keyMaterial
mongodb/libmongocrypt pull request #334
Opened 2022-05-11 11:54 UTC by addaleax

2022-05-16 13:37 UTC, durran requested changes
Spec test changes part of NODE-4110.

@addaleax Do we need to wait on the spec to merge first before merging this?

2022-05-16 13:37 UTC, durran commented on bindings/node/index.d.ts
> +  provider?: ClientEncryptionDataKeyProvider;
The spec doesn't have this as optional - is there a case where it's not provided?

2022-05-16 14:03 UTC, addaleax commented
> @addaleax Do we need to wait on the spec to merge first before merging this?

@durran Up to you – it would make our lives a bit easier if it's released earlier, I would be fine with it as long as everything is tagged as `@experimental` anyway 🙂

2022-05-17 14:25 UTC, durran approved these changes

2022-05-18 20:26 UTC, merged