feat(NODE-4294): mark queryable encryption options beta
mongodb/libmongocrypt pull request #380
Opened 2022-06-27 13:35 UTC by durran

Marks previous experimental options as beta/Public Technical Preview.

2022-06-27 15:36 UTC, nbbeeken requested changes

2022-06-27 15:36 UTC, nbbeeken commented on bindings/node/index.d.ts
> +  /** @beta Public Technical Preview: The id of the index key. */
Talked in standup
`@experimental: Public Technical Preview: The id of the index key.`

2022-06-27 15:36 UTC, nbbeeken commented on bindings/node/index.d.ts
> +  /** @beta Public Technical Preview: The qwuery type supported */
```suggestion
  /** @beta Public Technical Preview: The query type supported */
```

2022-06-28 13:45 UTC, durran commented on bindings/node/index.d.ts
> +  /** @beta Public Technical Preview: The qwuery type supported */
Updated.

2022-06-28 15:34 UTC, nbbeeken approved these changes

2022-06-28 15:35 UTC, merged