fix(NODE-4260): mongocrypterror has name getter
mongodb/libmongocrypt pull request #383
Opened 2022-06-28 17:21 UTC by durran

Switch the `name` property of `MongoCryptError` to a getter in order to avoid the property setting errors caused by bulk write errors in the Node driver.

2022-06-29 08:17 UTC, addaleax approved these changes

2022-06-29 13:45 UTC, nbbeeken approved these changes
Lgtm!

2022-06-29 20:46 UTC, dariakp requested changes
Is there any sort of regression test we can add against the actual reported issue?

2022-06-30 11:49 UTC, durran commented
> Is there any sort of regression test we can add against the actual reported issue?

https://github.com/mongodb/node-mongodb-native/pull/3305 has the test since the error doesn't come from this library but rather the behaviour in our driver errors.

2022-06-30 17:14 UTC, merged