CSHARP-4944: Enable use of native crypto in libmongocrypt bindings
mongodb/libmongocrypt pull request #796
Opened 2024-04-29 17:38 UTC by adelinowona

### Description
Use libmongocrypt native crypto when available.

### What's changing

- Bundle crypto-enabled libmongocrypt on Mac.
- On linux continue to bundle crypto-disabled libmongocrypt, but inform users to install the crypto-enabled libmongocrypt on their system and use the new environment variable `LIBMONGOCRYPT_PATH` to make it available to the driver. If `LIBMONGOCRYPT_PATH` is not set then we default to using the packaged crypto-disabled libmongocrypt.

### Performance Results

#### Using crypto-disabled libmongocrypt:
| Method                     | ThreadsCount | Mean        | Error     | StdDev    | Median      |
|--------------------------- |------------- |------------:|----------:|----------:|------------:|
| BulkDecryptionUsingBinding | 1            |    50.83 ms |  0.975 ms |  2.279 ms |    49.70 ms |
| BulkDecryptionUsingBinding | 2            |    71.34 ms |  1.422 ms |  3.090 ms |    71.32 ms |
| BulkDecryptionUsingBinding | 8            |   766.59 ms | 23.535 ms | 69.393 ms |   776.18 ms |
| BulkDecryptionUsingBinding | 64           | 5,575.51 ms | 91.840 ms | 85.907 ms | 5,581.51 ms |

#### Using crypto-enabled libmongocrypt:
| Method                     | ThreadsCount | Mean      | Error    | StdDev   |
|--------------------------- |------------- |----------:|---------:|---------:|
| BulkDecryptionUsingBinding | 1            |  22.03 ms | 0.103 ms | 0.096 ms |
| BulkDecryptionUsingBinding | 2            |  22.89 ms | 0.117 ms | 0.104 ms |
| BulkDecryptionUsingBinding | 8            |  30.69 ms | 0.564 ms | 0.554 ms |
| BulkDecryptionUsingBinding | 64           | 201.37 ms | 1.997 ms | 1.559 ms |

2024-04-30 21:04 UTC, BorisDog requested changes
Few minor questions.

2024-05-02 21:20 UTC, adelinowona commented on bindings/cs/MongoDB.Libmongocrypt/LibraryLoader.cs
> +            private static readonly string[] _suffixPaths =
Done

2024-05-02 21:20 UTC, adelinowona commented on bindings/cs/README.md
> +*Note*: You can use the ```LIBMONGOCRYPT_PATH``` environment variable to load a locally installed
Done

2024-05-02 21:20 UTC, adelinowona commented on bindings/cs/MongoDB.Libmongocrypt/CryptClientFactory.cs
> +                // mongocrypt_is_crypto_available is only available in libmongocrypt version >= 1.9
Good point! Done

2024-05-02 23:00 UTC, BorisDog requested changes
minor comments

2024-05-07 15:55 UTC, adelinowona commented on bindings/cs/MongoDB.Libmongocrypt/CryptClientFactory.cs
> +            var cryptoAvailable = Version.Parse(Library.Version) >= Version.Parse("1.9") && Library.mongocrypt_is_crypto_available();
Done

2024-05-07 17:41 UTC, BorisDog requested changes

2024-05-07 17:41 UTC, BorisDog commented on bindings/cs/MongoDB.Libmongocrypt/CryptClientFactory.cs
> +        private static readonly Version __s_libVersionWithMongocryptIsCryptoAvailable = Version.Parse("1.9");
Consider:
`private static readonly Version __mongocryptIsCryptoAvailableMinVersion = Version.Parse("1.9");`

2024-05-07 17:41 UTC, BorisDog commented on bindings/cs/README.md
> +libmongocrypt build. You should specify the absolute path to the libmongocrypt library itself, not just the containing folder.  For example on Linux:
I think this comment got lost:
https://github.com/mongodb/libmongocrypt/pull/796#discussion_r1588510088

2024-05-07 17:41 UTC, BorisDog commented on bindings/cs/MongoDB.Libmongocrypt/LibraryLoader.cs
> +            private static readonly string[] __s_suffixPaths =
I am sorry for confusion, I wanted to write  `__suffixPaths`  instead  `___s_suffixPaths `

2024-05-07 18:52 UTC, BorisDog approved these changes
LGTM

2024-05-23 14:53 UTC, merged