PYTHON-4547 Test against Python 3.13 beta
mongodb/libmongocrypt pull request #857
Opened 2024-07-10 15:12 UTC by blink1073

2024-07-10 22:57 UTC, NoahStapp approved these changes

2024-07-10 22:57 UTC, NoahStapp requested changes

2024-07-11 12:17 UTC, blink1073 commented on .github/workflows/test-python.yml
> +        python-version: ["3.8", "3.13"]
It is covered by EVG, we did the same in PyMongo.

2024-07-12 16:29 UTC, ShaneHarvey approved these changes

2024-07-12 16:31 UTC, merged