MONGOCRYPT-755 Implement StrEncode
mongodb/libmongocrypt pull request #928
Opened 2024-12-20 20:09 UTC by marksg07

2025-01-02 21:29 UTC, erwee requested changes

2025-01-02 21:29 UTC, erwee commented on src/mc-text-search-str-encode.c
> +                                                   const mc_FLE2SubstringInsertSpec_t *spec) {
This function also needs `beta` and `gamma` parameters which are the code-point lengths, not the byte length.

2025-01-06 21:35 UTC, marksg07 commented on src/mc-text-search-str-encode-private.h
> +} mc_str_encode_sets_t;
done

2025-01-06 21:35 UTC, marksg07 commented on src/mc-text-search-str-encode.c
> +                                                   const mc_FLE2SubstringInsertSpec_t *spec) {
done (folded codepoint len is inside the base string)

2025-01-06 21:35 UTC, marksg07 commented on src/mc-text-search-str-encode.c
> +    const char *folded_str = spec->v;
done

2025-01-07 16:19 UTC, marksg07 commented on src/mc-text-search-str-encode.c
> +    sets.exact_len = spec->len;
done

2025-01-07 16:20 UTC, marksg07 commented on src/mc-text-search-str-encode.c
> +    sets.base_len = spec->len + 1;
done

2025-01-09 18:11 UTC, erwee requested changes

2025-01-09 18:11 UTC, erwee commented on src/mc-text-search-str-encode.c
> +                mc_substring_set_insert(set, i, j, idx++, 1);
I think we need to remove duplicate substrings from this set, so we'll need some kind of unordered set/prefix tree data structure here.

2025-01-09 19:32 UTC, marksg07 commented on src/mc-text-search-str-encode.c
> +    if (unfolded_codepoint_len > spec->mlen || cbclen < spec->lb) {
Oh, so if a string is longer than mlen, we are throwing an error? I thought we were allowing this and just having it only be indexed by exact match?

2025-01-09 19:34 UTC, marksg07 commented on src/mc-text-search-str-encode.c
> +                mc_substring_set_insert(set, i, j, idx++, 1);
Oh, so that we don't return duplicate results when we search for a particular substring... Makes sense. I'll use a trie instead to dedupe.

2025-01-09 19:37 UTC, erwee commented on src/mc-text-search-str-encode.c
> +    if (unfolded_codepoint_len > spec->mlen || cbclen < spec->lb) {
No, we decided to forbid it during the technical design review, due to concerns from product that it could be misleading to users if we just silently insert but not index the string. Since there's no proper way to warn the user through the mongocrypt/driver, the safest approach is to just fail with an error.

2025-01-09 20:50 UTC, erwee requested changes

2025-01-09 20:50 UTC, erwee commented on src/mc-text-search-str-encode.c
> +    uint32_t msize = calc_number_of_substrings(padded_len, spec->lb, spec->ub);
Put a giant comment here to explain your simplification of the `msize` formula, so it's easy to correlate it with the paper:
```
    //
    // At this point, it is established that:
    //     beta <= mlen
    //     lb <= cbclen
    //     lb <= ub <= mlen
    //
    // So, the following formula for msize in the OST paper:
    //     maxkgram_1 = sum_(j=lb, ub, (mlen - j + 1))
    //     maxkgram_2 = sum_(j=lb, min(ub, cbclen), (cbclen - j + 1))
    //     msize      = min(maxkgram_1, maxkgram_2)
    // can be simplified to:
    //     msize      = sum_(j=lb, min(ub, cbclen), (min(mlen, cbclen) - j + 1))
    //
    // because if cbclen <= ub, then it follows that cbclen <= ub <= mlen, and so
    //     maxkgram_1 = sum_(j=lb, ub, (mlen - j + 1))          # as above
    //     maxkgram_2 = sum_(j=lb, cbclen, (cbclen - j + 1))    # less or equal to maxkgram_1
    //     msize      = maxkgram_2
    // and if cbclen > ub, then it follows that:
    //     maxkgram_1 = sum_(j=lb, ub, (mlen - j + 1))          # as above
    //     maxkgram_2 = sum_(j=lb, ub, (cbclen - j + 1))        # same sum bounds as maxkgram_1
    //     msize      = sum_(j=lb, ub, (min(mlen, cbclen) - j + 1))
    // in both cases, msize can be rewritten as:
    //     msize      = sum_(j=lb, min(ub, cbclen), (min(mlen, cbclen) - j + 1))
    //
```

Also, shouldn't the third parameter here be `MIN(spec->ub, cbclen)` ?

2025-01-10 23:07 UTC, marksg07 commented on src/mc-text-search-str-encode.c
> +    uint32_t msize = calc_number_of_substrings(padded_len, spec->lb, spec->ub);
We do the MIN inside calc_number_of_substrings, in the calculation of `largest_substr`.

2025-01-13 21:18 UTC, marksg07 commented on src/mc-text-search-str-encode.c
> +    sets->substring_set = NULL;
done

2025-01-13 21:18 UTC, marksg07 commented on src/mc-text-search-str-encode-private.h
> +    uint32_t len;
done

2025-01-13 21:18 UTC, marksg07 commented on src/mc-text-search-str-encode.c
> +#define MIN(a, b) (((a) < (b)) ? (a) : (b))
done

2025-01-13 21:18 UTC, marksg07 commented on src/mc-text-search-str-encode.c
> +    if (unfolded_codepoint_len > spec->mlen || cbclen < spec->lb) {
done

2025-01-13 21:19 UTC, marksg07 commented on src/mc-text-search-str-encode.c
> +    uint32_t msize = calc_number_of_substrings(padded_len, spec->lb, spec->ub);
done

2025-01-15 19:34 UTC, erwee requested changes

2025-01-15 19:34 UTC, erwee commented on src/mc-text-search-str-encode.c
> +    //     msize      = sum_(j=lb, min(ub, cbclen), (min(mlen, cbclen) - j + 1))
On second thought, maybe let's just keep this simple and calculate it the way it's done in the paper?
```
uint32_t maxkgram_1 = calc_number_of_substrings(mlen, spec->lb, spec->ub);
uint32_t maxkgram_2 = calc_number_of_substrings(cbclen, spec->lb, BSON_MIN(spec->ub, cbclen));
uint32_t msize = BSON_MIN(maxkgram_1, maxkgram_2);
```

2025-01-15 21:04 UTC, marksg07 commented on src/mc-str-encode-string-sets.c
> +    if (base_start_idx > base_end_idx || base_end_idx >= set->base_string->codepoint_len) {
I like having `codepoint_len` as the length of the `codepoint_offsets` array. We give the fake byte its own codepoint offset, so I feel it should be included in the length. What I could do is, since there's nothing actually programmatically wrong with allowing `base_end_idx == set->base_string->codepoint_len`, just allow that case but never use it. We can verify in testing (well, we already do) that we are never actually inserting the bad byte.

2025-01-15 21:11 UTC, marksg07 commented on src/mc-text-search-str-encode.c
> +    //     msize      = sum_(j=lb, min(ub, cbclen), (min(mlen, cbclen) - j + 1))
Eh, I don't like doing more calculations just in order to match the paper. I feel that the variable names and the inline comments give enough reason for why this counting method is correct -- it's clear that we are padding the length to the lesser of cbclen or mlen, and then calculating how many substrings between length lb and ub there would be if the string actually was that max padded length.

2025-01-15 21:59 UTC, marksg07 commented on src/mc-str-encode-string-sets.c
> +    it->cur_node = NULL;
Good point. Fixed.

2025-01-16 16:48 UTC, erwee approved these changes

2025-01-17 15:09 UTC, kevinAlbs reviewed
Nice work. Only substantial comment is to limit string lengths to prevent possible overflows.

2025-01-22 14:20 UTC, kevinAlbs approved these changes

2025-01-22 20:57 UTC, merged